version: '3'

services:
  djangoapp:
    build: .
    volumes:
      - .:/opt/services/djangoapp/src
      - socket_volume:/opt/services/djangoapp/socket
      - static_volume:/opt/services/djangoapp/static
      - media_volume:/opt/services/djangoapp/media

  nginx:
    image: nginx:1.19.1
    ports:
      - 8080:80
    volumes:
      - ./config/nginx/conf.d:/etc/nginx/conf.d
      - socket_volume:/opt/services/djangoapp/socket
      - static_volume:/opt/services/djangoapp/static
      - media_volume:/opt/services/djangoapp/media
    depends_on:
      - djangoapp

volumes:
  socket_volume:
  static_volume:
  media_volume: